sudo: false
language: python

matrix:
  include:
    # dropped Python 2.6 because I found OrderedDict (new in 2.7) very useful
    - python: 2.7
    # dropped Python 3.2 because coverage.py and python-codacy-coverage don't really support it
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get install -y liblz4-tool

# dependencies from requirements.txt are automatically installed

# command to run tests
script: coverage run -m pytest && coverage xml && python-codacy-coverage -r coverage.xml

env:
  global:
    - secure: fSYY1dfS9KLzYVgf1ZhHw4PTBmFzI9RORHxmq2w5y4WlzbXw81/aIfsNPWBtaXz8ovtH8AZ/vaqzilMpCkj1zJJV8QkB61c/3YsNnUKkCu3T8/pkjAeI9Rrg/2dpet6/kkVd6SiZOfo0WNuGtT0PXIOIisslU/5WEZm7npO6p3idUsh7GqfOTj4Ndw9e4WbP5FJYXFHuxLpbRzOxQGBB98J3D2OjVawlLdtz9t85iol+8Jd6WgofwXMR0d37vOkII5rtfv0iskBdW5ZnFQRNp6Aetw4zSRuBlLOgXdh+5sSd1LQwirgLsHJC1JvgNQQMK+DdazLK0CVRqSdfIj6Yac/QBGDangN6P3Gf3eKsADTwWVTopo4sulybya8TK3p60sg2m0bdWVVoUCT/0+41Lkzx0Zvyt8opXUqk6PWM/gxrBxXJP7VIBIgdVzhM1VUbagAi3mu6WJLqby5cKQqr8wSW0j0JDUU3QDx2nWE6uOyjMJDq9fFbtDG6yMTEKzl4Z672WZixJIE/4ckXk5q40LQJ+syJfxuLwP5BojuZe0685sJ/8Hydh5ygX/GcvXJxtvqp3oseJxp2DDaUPQL7JJ3CcxTqlGLw1WEuIvojxHocKvACHpDrWRsz5Vj7TQFB3PDWXKVJcuDY1HHotlzn6k/cJseWHg3pvbWjI3Mxfcg=
