sudo: false
language: python

matrix:
  include:
    # dropped Python 2.6 because I found OrderedDict (new in 2.7) very useful
    - python: 2.7
    # dropped Python 3.2 because coverage.py and python-codacy-coverage don't really support it
    # dropped Python 3.3 because pycryptodome doesn't support it
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.9
    - python: 3.10
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get install -y liblz4-tool

# dependencies from requirements.txt are automatically installed

# command to run tests
script: coverage run -m pytest && coverage xml && python-codacy-coverage -r coverage.xml
